# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='published',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
