# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
